// @vitest-environment jsdom
import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { render,screen,fireEvent,waitFor,cleanup } from "@testing-library/react";
import { ChecklistTarefa } from "../../src/components/tarefas/checklist-tarefa";
const api=vi.hoisted(()=>({listar:vi.fn(),criar:vi.fn(),editar:vi.fn(),remover:vi.fn(),ordenar:vi.fn()}));
vi.mock("../../src/lib/api/checklist",()=>({listarChecklist:api.listar,criarItemChecklist:api.criar,editarItemChecklist:api.editar,removerItemChecklist:api.remover,ordenarChecklist:api.ordenar}));
const item={id:"item",texto:"Preparar pauta",concluido:false,ordem:0,versao:0,criadaPor:{id:"eu",nome:"Ana"},criadaEm:"2026-10-07T12:00:00Z",atualizadaEm:"2026-10-07T12:00:00Z"};
const lista={items:[item],total:1,concluidos:0,podeEditar:true};
beforeEach(()=>{vi.clearAllMocks();api.listar.mockResolvedValue(lista);api.criar.mockResolvedValue(lista);api.editar.mockResolvedValue({...lista,items:[{...item,concluido:true,versao:1}],concluidos:1});api.remover.mockResolvedValue({...lista,items:[],total:0});api.ordenar.mockResolvedValue(lista);});
afterEach(cleanup);
it("mostra progresso e permite concluir o item",async()=>{render(<ChecklistTarefa tarefaId="tarefa"/>);expect(await screen.findByText("0 de 1")).toBeTruthy();fireEvent.click(screen.getByRole("checkbox"));await waitFor(()=>expect(api.editar).toHaveBeenCalledWith("tarefa",item,item.texto,true));expect(await screen.findByText("1 de 1")).toBeTruthy();});
it("adiciona item por submit e limpa campo somente após sucesso",async()=>{render(<ChecklistTarefa tarefaId="tarefa"/>);const input=await screen.findByLabelText("Novo item");fireEvent.change(input,{target:{value:"Conferir materiais"}});fireEvent.submit(input.closest("form")!);await waitFor(()=>expect(api.criar).toHaveBeenCalledWith("tarefa","Conferir materiais"));expect((input as HTMLInputElement).value).toBe("");});
it("edição preserva versão e remoção exige confirmação",async()=>{render(<ChecklistTarefa tarefaId="tarefa"/>);fireEvent.click(await screen.findByRole("button",{name:"Editar Preparar pauta"}));const input=screen.getByLabelText("Texto do item");fireEvent.change(input,{target:{value:"Pauta revisada"}});fireEvent.submit(input.closest("form")!);await waitFor(()=>expect(api.editar).toHaveBeenCalledWith("tarefa",item,"Pauta revisada",false));fireEvent.click(screen.getByRole("button",{name:"Remover Preparar pauta"}));expect(api.remover).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Confirmar remoção"}));await waitFor(()=>expect(api.remover).toHaveBeenCalled());});
it("ordenação envia conjunto completo para evitar sobrescrita",async()=>{const segundo={...item,id:"segundo",texto:"Materiais",ordem:1};api.listar.mockResolvedValue({...lista,items:[item,segundo],total:2});render(<ChecklistTarefa tarefaId="tarefa"/>);fireEvent.click(await screen.findByRole("button",{name:"Mover Materiais para cima"}));await waitFor(()=>expect(api.ordenar).toHaveBeenCalledWith("tarefa",[segundo,item]));});
it("somente leitura não oferece mutações e texto não vira HTML",async()=>{api.listar.mockResolvedValue({...lista,items:[{...item,texto:"<script>alert(1)</script>"}],podeEditar:false});render(<ChecklistTarefa tarefaId="tarefa"/>);expect(await screen.findByText("<script>alert(1)</script>")).toBeTruthy();expect(screen.queryByLabelText("Novo item")).toBeNull();expect((screen.getByRole("checkbox") as HTMLInputElement).disabled).toBe(true);expect(document.querySelector("script")).toBeNull();});
it("falha permite retry e vazio mantém formulário",async()=>{api.listar.mockRejectedValueOnce(new Error("Serviço indisponível"));render(<ChecklistTarefa tarefaId="tarefa"/>);await screen.findByText("Serviço indisponível");api.listar.mockResolvedValue({...lista,items:[],total:0});fireEvent.click(screen.getByRole("button",{name:"Tentar novamente"}));expect(await screen.findByText("Nenhum item no checklist.")).toBeTruthy();expect(screen.getByLabelText("Novo item")).toBeTruthy();});
