// @vitest-environment jsdom
import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { render,screen,fireEvent,waitFor,cleanup } from "@testing-library/react";
import { DetalheConteudo } from "../../src/components/conteudos/detalhe-conteudo";
import { ListaConteudos } from "../../src/components/conteudos/lista-conteudos";
import type { Conteudo } from "../../src/lib/api/conteudos";
const api=vi.hoisted(()=>({criar:vi.fn(),editar:vi.fn(),arquivar:vi.fn(),listar:vi.fn(),buscar:vi.fn(),opcoes:vi.fn()}));
vi.mock("../../src/lib/api/conteudos",async original=>({...await original<object>(),criarConteudo:api.criar,editarConteudo:api.editar,arquivarConteudo:api.arquivar,listarConteudos:api.listar,buscarConteudo:api.buscar,opcoesConteudos:api.opcoes}));
const opcoes={equipes:[{id:"equipe",nome:"Comunicação"}],responsaveis:[{id:"pessoa",nome:"Ana"}],eventos:[],projetos:[]};
const conteudo:Conteudo={id:"conteudo",titulo:"Peça da comunidade",briefing:"<script>texto simples</script>",canal:"INSTAGRAM",formato:"CARROSSEL",status:"EM_REVISAO",equipe:opcoes.equipes[0],responsavel:opcoes.responsaveis[0],publicacaoPlanejada:"2026-10-07",eventoId:"evento",projetoId:"projeto",criadaPor:{id:"autora",nome:"Autora"},versao:2,criadaEm:"2026-10-07T12:00:00Z",atualizadaEm:"2026-10-07T12:00:00Z",arquivada:false,capacidades:{editar:true,arquivar:true,verEvento:true,verProjeto:true}};
beforeEach(()=>{vi.clearAllMocks();HTMLDialogElement.prototype.showModal=function(){this.setAttribute("open","");};HTMLDialogElement.prototype.close=function(){this.removeAttribute("open");};api.opcoes.mockResolvedValue(opcoes);api.criar.mockResolvedValue(conteudo);api.editar.mockResolvedValue(conteudo);api.arquivar.mockResolvedValue(conteudo);api.listar.mockResolvedValue({items:[conteudo],total:1,page:0,size:25});api.buscar.mockResolvedValue(conteudo);});afterEach(cleanup);
it("apresenta briefing textual, data e vínculos conforme acesso",()=>{render(<DetalheConteudo inicial={conteudo} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.getByText("<script>texto simples</script>")).toBeTruthy();expect(screen.getByRole("link",{name:"Abrir evento vinculado"}).getAttribute("href")).toBe("/eventos?abrir=evento");expect(screen.getByText("7 de outubro de 2026")).toBeTruthy();});
it("somente leitura oculta mutações e links sem permissão",()=>{render(<DetalheConteudo inicial={{...conteudo,capacidades:{editar:false,arquivar:false,verEvento:false,verProjeto:false}}} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.queryByRole("button",{name:"Editar conteúdo"})).toBeNull();expect(screen.queryByRole("link",{name:"Abrir evento vinculado"})).toBeNull();});
it("edição preserva date-only e vínculos históricos",async()=>{render(<DetalheConteudo inicial={conteudo} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Editar conteúdo"}));await waitFor(()=>expect(api.opcoes).toHaveBeenCalled());fireEvent.change(screen.getByLabelText("Status"),{target:{value:"PUBLICADO"}});fireEvent.submit(screen.getByRole("button",{name:"Salvar conteúdo"}).closest("form")!);await waitFor(()=>expect(api.editar).toHaveBeenCalled());expect(api.editar.mock.calls[0][1]).toMatchObject({publicacaoPlanejada:"2026-10-07",eventoId:"evento",projetoId:"projeto",status:"PUBLICADO"});});
it("arquivo exige confirmação",async()=>{render(<DetalheConteudo inicial={conteudo} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Arquivar conteúdo"}));expect(api.arquivar).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Confirmar arquivamento"}));await waitFor(()=>expect(api.arquivar).toHaveBeenCalledWith(conteudo));});
it("lista abre recurso e apresenta erro com retry",async()=>{api.listar.mockRejectedValueOnce(new Error("Serviço indisponível"));render(<ListaConteudos opcoes={opcoes} podeCriar/>);await screen.findByText("Serviço indisponível");fireEvent.click(screen.getByRole("button",{name:"Tentar novamente"}));fireEvent.click(await screen.findByRole("button",{name:"Abrir conteúdo Peça da comunidade"}));expect(await screen.findByText("Detalhes do conteúdo")).toBeTruthy();});
it("conflito mantém formulário e briefing",async()=>{api.editar.mockRejectedValueOnce(new Error("Este conteúdo foi atualizado."));render(<DetalheConteudo inicial={conteudo} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Editar conteúdo"}));await waitFor(()=>expect(api.opcoes).toHaveBeenCalled());fireEvent.submit(screen.getByRole("button",{name:"Salvar conteúdo"}).closest("form")!);expect(await screen.findByText("Este conteúdo foi atualizado.")).toBeTruthy();expect(screen.getByLabelText("Briefing")).toBeTruthy();});
