// @vitest-environment jsdom
import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { render,screen,fireEvent,waitFor,cleanup } from "@testing-library/react";
import { DetalheEvento } from "../../src/components/eventos/detalhe-evento";
import { ListaEventos } from "../../src/components/eventos/lista-eventos";
import { formatarHorarioEvento,type Evento } from "../../src/lib/api/eventos";
const api=vi.hoisted(()=>({criar:vi.fn(),editar:vi.fn(),arquivar:vi.fn(),listar:vi.fn(),buscar:vi.fn(),opcoes:vi.fn()}));
vi.mock("../../src/lib/api/eventos",async original=>({...await original<object>(),criarEvento:api.criar,editarEvento:api.editar,arquivarEvento:api.arquivar,listarEventos:api.listar,buscarEvento:api.buscar,opcoesEventos:api.opcoes}));
const opcoes={equipes:[{id:"equipe",nome:"Comunicação"}],responsaveis:[{id:"pessoa",nome:"Ana"}]};
const evento:Evento={id:"evento",nome:"Talk de tecnologia",descricao:"Descrição",formato:"HIBRIDO",status:"PLANEJADO",equipe:opcoes.equipes[0],inicio:"2026-10-07T18:00:00Z",fim:"2026-10-07T19:00:00Z",zona:"America/Bahia",inicioLocal:"2026-10-07T15:00:00",fimLocal:"2026-10-07T16:00:00",local:"Sala",link:"https://example.test/encontro",notas:null,responsaveis:[{id:"pessoa",nome:"Ana"}],criadaPor:{id:"autora",nome:"Autora"},versao:2,criadaEm:"2026-10-07T12:00:00Z",atualizadaEm:"2026-10-07T12:00:00Z",arquivada:false,capacidades:{editar:true,arquivar:true}};
beforeEach(()=>{vi.clearAllMocks();HTMLDialogElement.prototype.showModal=function(){this.setAttribute("open","");};HTMLDialogElement.prototype.close=function(){this.removeAttribute("open");};api.opcoes.mockResolvedValue(opcoes);api.criar.mockResolvedValue(evento);api.editar.mockResolvedValue(evento);api.arquivar.mockResolvedValue(evento);api.listar.mockResolvedValue({items:[evento],total:1,page:0,size:25});api.buscar.mockResolvedValue(evento);});afterEach(cleanup);
it("apresenta horário no fuso do encontro e link seguro",()=>{render(<DetalheEvento inicial={evento} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.getByText("America/Bahia")).toBeTruthy();expect(formatarHorarioEvento(evento.inicio,evento.zona)).toContain("15:00");expect(formatarHorarioEvento(evento.inicio,"Europe/Lisbon")).toContain("19:00");const link=screen.getByRole("link",{name:"Abrir link do evento"});expect(link.getAttribute("rel")).toBe("noopener noreferrer");});
it("leitura não oferece controles de edição ou arquivo",()=>{render(<DetalheEvento inicial={{...evento,capacidades:{editar:false,arquivar:false}}} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.queryByRole("button",{name:"Editar evento"})).toBeNull();expect(screen.queryByRole("button",{name:"Arquivar evento"})).toBeNull();});
it("edição envia horário local e zona sem conversão ingênua",async()=>{render(<DetalheEvento inicial={evento} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Editar evento"}));await waitFor(()=>expect(api.opcoes).toHaveBeenCalled());fireEvent.change(screen.getByLabelText("Fuso do evento"),{target:{value:"Europe/Lisbon"}});fireEvent.submit(screen.getByRole("button",{name:"Salvar evento"}).closest("form")!);await waitFor(()=>expect(api.editar).toHaveBeenCalled());expect(api.editar.mock.calls[0][1]).toMatchObject({inicioLocal:"2026-10-07T15:00",fimLocal:"2026-10-07T16:00",zona:"Europe/Lisbon",responsavelIds:["pessoa"]});});
it("arquivamento exige confirmação",async()=>{render(<DetalheEvento inicial={evento} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Arquivar evento"}));expect(api.arquivar).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Confirmar arquivamento"}));await waitFor(()=>expect(api.arquivar).toHaveBeenCalledWith(evento));});
it("lista abre detalhe existente e oferece filtros",async()=>{render(<ListaEventos opcoes={opcoes} podeCriar/>);fireEvent.click(await screen.findByRole("button",{name:"Abrir evento Talk de tecnologia"}));expect(await screen.findByText("Detalhes do evento")).toBeTruthy();expect(api.buscar).toHaveBeenCalledWith("evento");});
it("vazio e erro têm retorno útil",async()=>{api.listar.mockRejectedValueOnce(new Error("Serviço indisponível"));render(<ListaEventos opcoes={opcoes} podeCriar={false}/>);await screen.findByText("Serviço indisponível");api.listar.mockResolvedValue({items:[],total:0,page:0,size:25});fireEvent.click(screen.getByRole("button",{name:"Tentar novamente"}));expect(await screen.findByText("Nenhum evento encontrado.")).toBeTruthy();expect(screen.queryByRole("button",{name:"Novo evento"})).toBeNull();});
it("conflito preserva formulário e resultado textual não vira HTML",async()=>{api.editar.mockRejectedValueOnce(new Error("Este evento foi atualizado."));render(<DetalheEvento inicial={{...evento,notas:"<script>texto</script>"}} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.getByText("<script>texto</script>")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Editar evento"}));await waitFor(()=>expect(api.opcoes).toHaveBeenCalled());fireEvent.submit(screen.getByRole("button",{name:"Salvar evento"}).closest("form")!);expect(await screen.findByText("Este evento foi atualizado.")).toBeTruthy();expect(screen.getByLabelText("Nome")).toBeTruthy();});
