// @vitest-environment jsdom
import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { render,screen,fireEvent,waitFor,cleanup } from "@testing-library/react";
import { DetalheReuniao } from "../../src/components/reunioes/detalhe-reuniao";
import { ListaReunioes } from "../../src/components/reunioes/lista-reunioes";
import { formatarHorarioReuniao,type Reuniao } from "../../src/lib/api/reunioes";
const api=vi.hoisted(()=>({criar:vi.fn(),editar:vi.fn(),arquivar:vi.fn(),listar:vi.fn(),buscar:vi.fn(),opcoes:vi.fn()}));
vi.mock("../../src/lib/api/reunioes",async original=>({...await original<object>(),criarReuniao:api.criar,editarReuniao:api.editar,arquivarReuniao:api.arquivar,listarReunioes:api.listar,buscarReuniao:api.buscar,opcoesReunioes:api.opcoes}));
const opcoes={equipes:[{id:"equipe",nome:"Comunicação"}],participantes:[{id:"pessoa",nome:"Ana"}]};
const reuniao:Reuniao={id:"reuniao",titulo:"Talk de tecnologia",pauta:"Pauta",tipo:"TALK",status:"AGENDADA",equipe:opcoes.equipes[0],inicio:"2026-10-07T18:00:00Z",fim:"2026-10-07T19:00:00Z",zona:"America/Bahia",inicioLocal:"2026-10-07T15:00:00",fimLocal:"2026-10-07T16:00:00",local:"Sala",link:"https://example.test/encontro",resultados:null,participantes:[{id:"pessoa",nome:"Ana",responsavel:true}],criadaPor:{id:"autora",nome:"Autora"},versao:2,criadaEm:"2026-10-07T12:00:00Z",atualizadaEm:"2026-10-07T12:00:00Z",arquivada:false,capacidades:{editar:true,arquivar:true}};
beforeEach(()=>{vi.clearAllMocks();HTMLDialogElement.prototype.showModal=function(){this.setAttribute("open","");};HTMLDialogElement.prototype.close=function(){this.removeAttribute("open");};api.opcoes.mockResolvedValue(opcoes);api.criar.mockResolvedValue(reuniao);api.editar.mockResolvedValue(reuniao);api.arquivar.mockResolvedValue(reuniao);api.listar.mockResolvedValue({items:[reuniao],total:1,page:0,size:25});api.buscar.mockResolvedValue(reuniao);});afterEach(cleanup);
it("apresenta horário no fuso do encontro e link seguro",()=>{render(<DetalheReuniao inicial={reuniao} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.getByText("America/Bahia")).toBeTruthy();expect(formatarHorarioReuniao(reuniao.inicio,reuniao.zona)).toContain("15:00");expect(formatarHorarioReuniao(reuniao.inicio,"Europe/Lisbon")).toContain("19:00");const link=screen.getByRole("link",{name:"Abrir link do encontro"});expect(link.getAttribute("rel")).toBe("noopener noreferrer");});
it("leitura não oferece controles de edição ou arquivo",()=>{render(<DetalheReuniao inicial={{...reuniao,capacidades:{editar:false,arquivar:false}}} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.queryByRole("button",{name:"Editar reunião"})).toBeNull();expect(screen.queryByRole("button",{name:"Arquivar reunião"})).toBeNull();});
it("edição envia horário local e zona sem conversão ingênua",async()=>{render(<DetalheReuniao inicial={reuniao} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Editar reunião"}));await waitFor(()=>expect(api.opcoes).toHaveBeenCalled());fireEvent.change(screen.getByLabelText("Fuso do encontro"),{target:{value:"Europe/Lisbon"}});fireEvent.submit(screen.getByRole("button",{name:"Salvar reunião"}).closest("form")!);await waitFor(()=>expect(api.editar).toHaveBeenCalled());expect(api.editar.mock.calls[0][1]).toMatchObject({inicioLocal:"2026-10-07T15:00",fimLocal:"2026-10-07T16:00",zona:"Europe/Lisbon",participanteIds:["pessoa"],responsavelIds:["pessoa"]});});
it("arquivamento exige confirmação",async()=>{render(<DetalheReuniao inicial={reuniao} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);fireEvent.click(screen.getByRole("button",{name:"Arquivar reunião"}));expect(api.arquivar).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Confirmar arquivamento"}));await waitFor(()=>expect(api.arquivar).toHaveBeenCalledWith(reuniao));});
it("lista abre detalhe existente e oferece filtros",async()=>{render(<ListaReunioes opcoes={opcoes} podeCriar/>);fireEvent.click(await screen.findByRole("button",{name:"Abrir reunião Talk de tecnologia"}));expect(await screen.findByText("Detalhes da reunião")).toBeTruthy();expect(api.buscar).toHaveBeenCalledWith("reuniao");});
it("vazio e erro têm retorno útil",async()=>{api.listar.mockRejectedValueOnce(new Error("Serviço indisponível"));render(<ListaReunioes opcoes={opcoes} podeCriar={false}/>);await screen.findByText("Serviço indisponível");api.listar.mockResolvedValue({items:[],total:0,page:0,size:25});fireEvent.click(screen.getByRole("button",{name:"Tentar novamente"}));expect(await screen.findByText("Nenhum encontro encontrado.")).toBeTruthy();expect(screen.queryByRole("button",{name:"Nova reunião / Talk"})).toBeNull();});
it("conflito preserva formulário e resultado textual não vira HTML",async()=>{api.editar.mockRejectedValueOnce(new Error("Esta reunião foi atualizada."));render(<DetalheReuniao inicial={{...reuniao,resultados:"<script>texto</script>"}} opcoes={opcoes} aoFechar={()=>{}} aoConcluir={()=>{}}/>);expect(screen.getByText("<script>texto</script>")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Editar reunião"}));await waitFor(()=>expect(api.opcoes).toHaveBeenCalled());fireEvent.submit(screen.getByRole("button",{name:"Salvar reunião"}).closest("form")!);expect(await screen.findByText("Esta reunião foi atualizada.")).toBeTruthy();expect(screen.getByLabelText("Título")).toBeTruthy();});
