"use client";

import { useState, useTransition } from "react";
import { addTeamMemberAction, archiveTeamAction, createTeamAction, removeTeamMemberAction, updateTeamAction } from "@/app/equipes/actions";
import { Button } from "./ui/button";
import { Input } from "./ui/input";

type Member = { user: { id: string; name: string; email: string } };
type Team = { id: string; name: string; description: string | null; parentId: string | null; members: Member[] };
type User = { id: string; name: string; email: string };
export function TeamManagement({ teams, users, canCreate, canEdit, canArchive, canMembers }: { teams: Team[]; users: User[]; canCreate: boolean; canEdit: boolean; canArchive: boolean; canMembers: boolean }) {
  const [pending, start] = useTransition(); const [message, setMessage] = useState("");
  const run = (work: () => Promise<{ ok: boolean; error?: string }>) => start(async () => { const result = await work(); setMessage(result.ok ? "Alteração salva." : result.error ?? "Não foi possível concluir a operação."); });
  const root = teams.find(team => team.parentId === null);
  return <div className="space-y-4">
    {canCreate && <form className="grid gap-4 rounded-2xl border border-border bg-card p-5 md:grid-cols-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => createTeamAction({ name: String(form.get("name")), description: String(form.get("description")), parentId: String(form.get("parentId")) })); }}><div><label className="text-sm font-medium" htmlFor="team-name">Nome</label><Input id="team-name" name="name" required disabled={pending} /></div><div><label className="text-sm font-medium" htmlFor="team-description">Descrição</label><Input id="team-description" name="description" disabled={pending} /></div><label className="space-y-2 text-sm"><span>Equipe superior</span><select name="parentId" defaultValue={root?.id} className="min-h-12 w-full rounded-xl border border-border bg-card px-3" disabled={pending}>{teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><div className="flex items-end"><Button type="submit" disabled={pending}>Criar equipe</Button></div></form>}
    {teams.map(team => <article key={team.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{team.name}</h3><p className="text-sm text-muted-foreground">{team.description || "Sem descrição"}</p></div>{team.parentId === null ? <span className="rounded-full bg-accent px-3 py-1 text-xs">Estrutural</span> : canArchive && <Button type="button" disabled={pending} className="bg-muted text-foreground hover:bg-border" onClick={() => run(() => archiveTeamAction(team.id))}>Arquivar</Button>}</div>
      {canEdit && team.parentId !== null && <form className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto]" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => updateTeamAction({ teamId: team.id, name: String(form.get("name")), description: String(form.get("description")), parentId: String(form.get("parentId")) })); }}><Input name="name" defaultValue={team.name} aria-label={`Nome de ${team.name}`} disabled={pending} /><Input name="description" defaultValue={team.description ?? ""} aria-label={`Descrição de ${team.name}`} disabled={pending} /><select name="parentId" defaultValue={team.parentId ?? ""} aria-label={`Equipe superior de ${team.name}`} className="min-h-12 rounded-xl border border-border bg-card px-3" disabled={pending}>{teams.filter(parent => parent.id !== team.id).map(parent => <option key={parent.id} value={parent.id}>{parent.name}</option>)}</select><Button type="submit" disabled={pending} className="md:col-span-3 md:justify-self-start">Salvar equipe</Button></form>}
      {canMembers && <div className="mt-5 border-t border-border pt-4"><h4 className="text-sm font-semibold">Integrantes</h4><ul className="mt-2 space-y-2">{team.members.map(member => <li key={member.user.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>{member.user.name} <span className="text-muted-foreground">({member.user.email})</span></span><Button type="button" disabled={pending} className="min-h-8 bg-muted px-3 py-1 text-xs text-foreground" onClick={() => run(() => removeTeamMemberAction(member.user.id, team.id))}>Remover</Button></li>)}</ul><form className="mt-3 flex flex-wrap gap-2" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => addTeamMemberAction(String(form.get("userId")), team.id)); }}><select name="userId" required className="min-h-11 flex-1 rounded-xl border border-border bg-card px-3" disabled={pending}><option value="">Adicionar integrante</option>{users.filter(user => !team.members.some(member => member.user.id === user.id)).map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><Button type="submit" disabled={pending}>Adicionar</Button></form></div>}
    </article>)}
    {message && <p role="status" className="text-sm">{message}</p>}
  </div>;
}
